---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test
  labels:
    app: test
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: test
        image: 488666820772.dkr.ecr.eu-central-1.amazonaws.com/test
        ports:
        - name: http
          containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata: 
 name: test-nodeport-service
spec:
  selector:   
    app: test
  type: NodePort
  ports: 
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30004
    protocol: TCP
