resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/zloyshaddar/test.git
    branch: master
    
jobs:
- name: deploy
  plan:
  - get: git-repo
  - put: k8s
    params:
      kubectl: apply -f git-repo/deploy.yaml
