resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.9"

resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/zloyshaddar/test.git
    branch: master
- name: k8s
    type: kubernetes
    source:
      kubeconfig: cluster.k8s.local
    
jobs:
- name: deploy
  plan:
  - get: git-repo
  - put: k8s
    params:
      kubectl: apply -f git-repo/deploy.yaml
